TvShowReader/Models/Episode.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TvShowReader.Models
{
  public class Episode
  {
    public int Number;

    public bool IsHD;

    public string Link;

    public string FullEpisodeNumber;
  }
}

TvShowReader/Models/SearchResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TvShowReader.Models
{
	public class SearchResultViewModel
	{
		public List<string> tvShowLinks;
	}
}

TvShowReader/Models/Season.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TvShowReader.Models
{
  public class Season
  {
    public int Number;

    public List<Episode> Episodes;
  }
}

TvShowReader/Models/TvShow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TvShowReader.Models
{
  public class TvShow
  {
    public string Name;

    public List<Season> Seasons;

    public TvShow()
    {

    }

    public TvShow(string name, List<string> episodes)
    {
      Name = name;

      Seasons = new List<Season>
      {
        new Season
        {
          Number = GetSeasonNumber(episodes.First()),
          Episodes = episodes.Select(e => new Episode {Number = GetEpisodeNumber(e), FullEpisodeNumber = e}).ToList()
        }
      };
    }

    private int GetSeasonNumber(string episodeFullNumber)
    {
      if (episodeFullNumber.Equals("\"Special\""))
      {
        return -1;
      }

      episodeFullNumber = CleanEpisodeFullNumber(episodeFullNumber);

      return int.Parse(episodeFullNumber.Split('x')[0]);
    }

    private int GetEpisodeNumber(string episodeFullNumber)
    {
      if (episodeFullNumber.Equals("\"Special\""))
      {
        return -1;
      }

      episodeFullNumber = CleanEpisodeFullNumber(episodeFullNumber);

      return int.Parse(episodeFullNumber.Split('x')[1]);
    }

    private string CleanEpisodeFullNumber(string episodeFullNumber)
    {
      return episodeFullNumber.Substring(1, episodeFullNumber.Length - 2);
    }
  }

}

TvShowReader/Models/TvShowViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using TvShowReader.Services;

namespace TvShowReader.Models
{
  public class TvShowViewModel
  {
    public Dictionary<string, List<Episode>> TvShows;
  }
}

TvShowReader/Controllers/AureliaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TvShowReader.Controllers
{
  public class AureliaController : Controller
  {
    // GET: Aurelia
    public ActionResult Index()
    {
      return View();
    }

    public ActionResult GetLastSearches()
    {
      return View("_LastSearches");
    }
  }
}

TvShowReader/Controllers/HomeController.cs
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TvShowReader.Converters;
using TvShowReader.Models;
using TvShowReader.Services;

namespace TvShowReader.Controllers
{
	public class HomeController : Controller
	{
    IEpisodeService episodeService = new OfflineEpisodeService();
    TvShowViewModelConverter converter = new TvShowViewModelConverter();

    public ActionResult Index()
		{
			return View();
		}

    public ActionResult NextEpisode()
    {
      var episodes = episodeService.GetEpisodes();

      TvShowViewModel model = converter.Convert(episodes);

      return View(model);
    }
  }
}

TvShowReader/Controllers/SearchController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using HtmlAgilityPack;

namespace TvShowReader.Controllers
{
  public class SearchController : Controller
  {
    public static List<string> LastSearches = new List<string>();
     
    [HttpGet]
    public JsonResult GetSearchResults(string tvShowName)
    {
      tvShowName = tvShowName.Replace(' ', '+');

      string url = "https://seriescr.com/?s=" + tvShowName;

      HtmlWeb web = new HtmlWeb();
      HtmlDocument doc;

      if (ConfigurationManager.AppSettings["UseProxy"] == "true")
      {
        doc = web.Load(url, ConfigurationManager.AppSettings["proxyAddress"], int.Parse(ConfigurationManager.AppSettings["proxyPort"]), ConfigurationManager.AppSettings["proxyLogin"], ConfigurationManager.AppSettings["proxyPassword"]);
      }
      else
      {
        doc = web.Load(url);
      }

      List<string> links = new List<string>();

      var elements = doc.DocumentNode.SelectNodes("//div[contains(@class, 'sbox')]");

      if (elements != null)
      {
        foreach (HtmlNode post in elements)
        {
          string linkForEpisode = post.ChildNodes.FindFirst("h2").ChildNodes.FindFirst("a").OuterHtml;
          linkForEpisode = linkForEpisode.Insert(linkForEpisode.IndexOf("title") - 1, "target=\"_blank\"");

          links.Add(linkForEpisode);
        }
      }

      return new JsonResult { Data = links, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
    }

    [HttpGet]
    public JsonResult GetLastSearches()
    {
      return new JsonResult { Data = LastSearches, JsonRequestBehavior = JsonRequestBehavior.AllowGet };
    }

    [HttpPost]
    public void SaveSearch(string query)
    {
      //jakiś zapis do pliku

      if (LastSearches.Contains(query) == false)
      {
        LastSearches.Add(query);
      }
      else
      {
        LastSearches.Remove(query);
        LastSearches.Add(query);
      }
    }
  }
}

TvShowReader/Views/Aurelia/Index.cshtml
@{
	Layout = null;
}

<!DOCTYPE html>

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	<title>Aurelia</title>
	@Styles.Render("~/Aurelia/styles")
</head>
<body>
	<div aurelia-app="main">
		<div class="splash">
			<div class="message">Aurelia Navigation Skeleton</div>
			<i class="fa fa-spinner fa-spin"></i>
		</div>
		<script src="jspm_packages/system.js"></script>
		<script src="config.js"></script>
		<script>
      System.import('aurelia-bootstrapper');
		</script>
	</div>
</body>
</html>

TvShowReader/Views/Aurelia/_LastSearches.cshtml
@{
	Layout = null;
}


	@Styles.Render("~/Aurelia/styles")

	<div aurelia-app="main">
		<div class="splash">
			<div class="message">Aurelia Navigation Skeleton</div>
			<i class="fa fa-spinner fa-spin"></i>
		</div>
		<script src="jspm_packages/system.js"></script>
		<script src="config.js"></script>
		<script>
      System.import('aurelia-bootstrapper');
		</script>
	</div>

TvShowReader/Views/Home/Index.cshtml
@{
	ViewBag.Title = "TvShowReader";
}

<link rel="stylesheet" href="~/Content/Loader.css">
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

<script type="text/javascript">
	function SearchTvShow(name) {
		$.ajax({
			type: "GET",
			url: '@Url.Action("GetSearchResults", "Search")',//"Search/GetSearchResults",
			data: { 'tvShowName': name },
			success: function (data) {
				console.log(data);
				if (data.length > 0) {
					LoadTable(data);
				} else {
					$("#searchResultsTable").append('<tr><td><h3>Brak wyników</h3></td></tr>');
				}
			}
		});
	}

	function LoadTable(result) {
		var rows = "";
		for (var i = 0; i < result.length; i++) {
			rows += '<tr><td>' + result[i] + '</td></tr>';
		}
		$("#searchResultsTable").append('<tr><th></th></td>');
		$("#searchResultsTable").append(rows);
	}

	function Search() {
		$("#searchResultsTable tbody tr").remove();

		$('#searchResults').show();

		var searchValue = $("#searchBox").val();
		SearchTvShow(searchValue);
		SaveSearchQuery(searchValue);
	}

	function LastSearchedLinkClicked(query) {
		$("#searchBox").val(query);
		Search(query);
	}

	function SaveSearchQuery(query) {
		$.ajax({
			type: "POST",
			url: '@Url.Action("SaveSearch", "Search")',//"/Search/SaveSearch",//
			data: { 'query': query },
			success: function () {
				console.log("Saved" + query);
			}
		});
	}

	function GetLastSearches() {
		$.ajax({
			type: "GET",
			url: '@Url.Action("GetLastSearches","Search")',//'@Url.Action("GetLastSearches","Search")',//"Search/GetLastSearches"//,
			data: {},
			success: function (data) {
				$("#LastSearches li").remove();
				var listItems = "";
				for (var i = 0; i < data.length; i++) {
					listItems += '<li><a href="#" id="LastSearchedQuery">' + data[i] + '</a></li>';
				}

				$('#LastSearches').append(listItems);

				$('#LastSearches a').click(function (e) {
					var query = $(this).text();
					LastSearchedLinkClicked(query);
				});
			}
		});
	}

	$(document).ready(function () {
		$('#searchResults').hide();

		$('#searchTvShow').click(function () {
			Search();
			GetLastSearches();
		});

		$('#LastSearches a').click(function (e) {
			console.log("Clicked");
			var query = $(this).text();
			LastSearchedLinkClicked(query);
		});

		$('#searchBox').keypress(function (event) {
			if (event.keyCode == 13 || event.which == 13) {
				Search();
				GetLastSearches();
				event.preventDefault();
			}
		});

		var $loadingPlace = $("#toBeLoaded");
		$(document).ajaxStart(function () {
			$loadingPlace.addClass("loader");
		});
		$(document).ajaxStop(function () {
			$loadingPlace.removeClass("loader");
		});

		GetLastSearches();
	});

</script>

<h1>Find latest episodes for:</h1>

<div>
	<div id="custom-search-input">
		<div class="input-group col-md-12">
			<input type="search" class="form-control input-lg" placeholder="Enter name of a tv show" id="searchBox" autofocus />
			<span class="input-group-btn">
				<button class="btn btn-info btn-lg" type="button" id="searchTvShow">
					<i class="glyphicon glyphicon-search"></i>
				</button>
			</span>
		</div>
	</div>
</div>

<div id="searchResults" class="row">
	<div id="toBeLoaded"></div>
	<h2>Search results:</h2>
	<table id="searchResultsTable" class=".table-striped"></table>
</div>

<div id="searchResultsArchive" class="row">
	<h2>Latest search results for:</h2>
	@Html.Partial("~/Views/Search/_LastSearches.cshtml")
</div>

TvShowReader/Views/Home/NextEpisode.cshtml
@{
	ViewBag.Title = "TvShowReader";
}
@model TvShowReader.Models.TvShowViewModel

<link rel="stylesheet" href="~/Content/Loader.css">
<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>

<script type="text/javascript">
	
	$(document).ready(function () {
	
	});

</script>


<div id="notWatchedEpisodes" class="row">

	<ul class="list-group">
		<li class="list-group-item">
			<span class="badge">@Model.TvShows..Episodes.Count</span>
			@Model.Name
			<div class="">
				<table id="searchResultsTable" class=".table-striped"></table>
			</div>
		</li>
	</ul>

</div>

TvShowReader/Views/Search/_LastSearches.cshtml
<script type="text/javascript">
	//function GetLastSearches() {
	//	$.ajax({
	//		type: "GET",
	//		url: "Search/GetLastSearches",
	//		data: {},
	//		success: function (data) {
	//			var listItems = "";
	//			for (var i = 0; i < data.length; i++) {
	//				listItems += '<li>' + data[i] + '</li>';
	//			}

	//			$('#LastSearches').append(listItems);
	//		}
	//	});
	//}

	//$(document).ready(function() {
	//	GetLastSearches();
	//});

</script>

<div class="list-group">
	<ul id="LastSearches">
		
	</ul>
</div>

TvShowReader/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>@ViewBag.Title</title>
	@Styles.Render("~/Content/css")
	@Scripts.Render("~/bundles/modernizr")
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				@Html.ActionLink("Tv Show Reader", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav">
					<li>@Html.ActionLink("Home", "Index", "Home")</li>
					<li>@Html.ActionLink("Next Episode", "NextEpisode", "Home")</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="container body-content">
		@RenderBody()
		<hr />
		<footer>
			<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
		</footer>
	</div>

	@Scripts.Render("~/bundles/jquery")
	@Scripts.Render("~/bundles/bootstrap")
	@RenderSection("scripts", required: false)
</body>
</html>